"""4th migration

Revision ID: d39dbd4edde0
Revises: fd7147f7a026
Create Date: 2020-12-03 17:53:12.566140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39dbd4edde0'
down_revision = 'fd7147f7a026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catagories', sa.Column('owner', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'catagories', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catagories', type_='foreignkey')
    op.drop_column('catagories', 'owner')
    # ### end Alembic commands ###
