"""4th migration

Revision ID: fd7147f7a026
Revises: fe53ac56eac6
Create Date: 2020-12-02 15:23:40.761158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7147f7a026'
down_revision = 'fe53ac56eac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('types', sa.Column('owner', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'types', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'types', type_='foreignkey')
    op.drop_column('types', 'owner')
    # ### end Alembic commands ###
